### ISSUE TITLE
Warnings when building for Arm under gcc11

### ISSUE THREAD

**Issue by bretambrose** [awslabs/aws-lc#184] opened 2021-07-01 19:47 UTC
### Problem:

While building for arm using gcc11, we are running into several warnings.  We can disable them locally in order to stay unblocked, but it would be ideal if they could get cleaned up eventually.

#### Relevant details

This is possibly not Arm-specific, but that may be the only CI build using gcc 11 at the moment.

AWS-LC commit: d0a5455417d80e68581e197d95720c3fb25e3926

stringop-overflow warning:
https://github.com/awslabs/aws-crt-java/runs/2958051434#step:2:401

array-parameter warning:
https://github.com/awslabs/aws-crt-java/runs/2964997874#step:2:423

System information: ubuntu 18 cross compiling Aws-crt-java for arm v6, v7, and v8

Build log: 
See links per-warning.

**Comment by samuel40791765** [comment] 2021-07-06 23:14
Hi, thanks for your report! 
We did some gcc11 build testing with x86, but none of the warnings that came up were similar to this. We're currently doing a further investigation to see if this is ARM specific and will get back to you soon.

**Comment by samuel40791765** [comment] 2021-07-10 00:42
I've been able to reproduce the `stringop-overflow warning` which seems to be a false positive on the memory initialization and assignment for CBS integers. We're going to be looking into a fix for this.
However, I'm having a bit of trouble recreating the `array-parameter warning` warnings from `Experimental warning suppression`. Do you have any build commands or details on what warnings were suppressed to recreate this?

**Comment by samuel40791765** [comment] 2021-07-13 21:43
Thanks for pointing this issue out. 
The `stringop-overflow` warning will be resolved with this PR: https://github.com/awslabs/aws-lc/pull/191
The `array-parameter` warning will be fixed with the latest BoringSSL merge https://github.com/awslabs/aws-lc/pull/174 which also ran into the same problem. https://github.com/google/boringssl/commit/92c6fbfc4c44dc8462d260d836020d2b793e7804#diff-26d3d0341a362f0855ef69b10c04ba4f976256d640e06b577359ce1fd3f4f297

**Comment by samuel40791765** [comment] 2021-07-15 20:01
Closing issue now that both PR fixes for warnings are merged.

**Closed by samuel40791765** 2021-07-15 20:01 UTC
