### ISSUE TITLE
cross compile  error

### ISSUE THREAD

**Issue by wildwindyevan** [awslabs/aws-lc#170] opened 2021-06-04 01:26 UTC
### Problem:

[CMakeError.log](https://github.com/awslabs/aws-lc/files/6595152/CMakeError.log)
 stops when cmaking aws-iot-device-sdk-cpp-v2

#### Relevant details
AWS-LC commit: (6b1bce0...)

System information: for linux, below info can be collected by running `uname -srvmp`
 * CPU architecture: ARM A7
 * CPU name: NXP imx6
 * OS:  ubuntu16

Build log: 
root@xxylin-virtual-machine:/home/wildwindy/NFS/AWSSDK/sdkv2/build# cmake -DCMAKE_INSTALL_PREFIX="/home/wildwindy/NFS/AWSSDK/sdkv2/install" -DBUILD_DEPS=ON  ../aws-iot-device-sdk-cpp-v2
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
-- Check for working C compiler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++
-- Check for working CXX compiler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AWS CRT C++ v0.13.8
-- CMake 3.15.2
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_WINAPI_DESKTOP
-- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Success
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW - Failed
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Failed
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Looking for pthread_attr_setaffinity_np
-- Looking for pthread_attr_setaffinity_np - found
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- The C compiler identification is GNU 4.9.1
-- Check for working C compiler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
-- Check for working C compiler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -- broken
CMake Error at /usr/local/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/wildwindy/NFS/AWSSDK/sdkv2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_a657f/fast && /usr/bin/make -f CMakeFiles/cmTC_a657f.dir/build.make CMakeFiles/cmTC_a657f.dir/build
    make[1]: Entering directory '/home/wildwindy/NFS/AWSSDK/sdkv2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_a657f.dir/testCCompiler.c.o
    /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc   -O2 -pipe -g -feliminate-unused-debug-types  -fPIE   -o CMakeFiles/cmTC_a657f.dir/testCCompiler.c.o   -c /home/wildwindy/NFS/AWSSDK/sdkv2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMak-- Configuring incomplete, errors occurred!
See also "/home/wildwindy/NFS/AWSSDK/sdkv2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeOutput.log".
See also "/home/wildwindy/NFS/AWSSDK/sdkv2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeError.log".
eTmp/testCCompiler.c
    Linking C executable cmTC_a657f
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a657f.dir/link.txt --verbose=1
    /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -O2 -pipe -g -feliminate-unused-debug-types   -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -rdynamic CMakeFiles/cmTC_a657f.dir/testCCompiler.c.o  -o cmTC_a657f 
    /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.9.1/ld: error: cmTC_a657f uses VFP register arguments, CMakeFiles/cmTC_a657f.dir/testCCompiler.c.o does not
    /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/4.9.1/ld: failed to merge target specific data of file CMakeFiles/cmTC_a657f.dir/testCCompiler.c.o
    collect2: error: ld returned 1 exit status
    CMakeFiles/cmTC_a657f.dir/build.make:86: recipe for target 'cmTC_a657f' failed
    make[1]: *** [cmTC_a657f] Error 1
    make[1]: Leaving directory '/home/wildwindy/NFS/AWSSDK/sdkv2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_a657f/fast' failed
    make: *** [cmTC_a657f/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:23 (enable_language)

CMake Error at crt/aws-crt-cpp/crt/aws-c-cal/cmake/modules/aws-lc.cmake:25 (message):
  Failed to configure aws-lc
Call Stack (most recent call first):
  crt/aws-crt-cpp/CMakeLists.txt:105 (include)

-- Configuring incomplete, errors occurred!
See also "/home/wildwindy/NFS/AWSSDK/sdkv2/build/CMakeFiles/CMakeOutput.log".
See also "/home/wildwindy/NFS/AWSSDK/sdkv2/build/CMakeFiles/CMakeError.log".

**Comment by torben-hansen** [comment] 2021-06-08 17:47
Hi, thanks for your report.

Looking at the error output I can see that CMake attempts to compile and link a small test program `testCCompiler.c`. This is a sanity check of your compilers ability to function, soemthing CMake does, and doesn't use any AWS-LC code. Extracting the specific build commands from the error log we can see it is independent of AWS-LC:
```
/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc   -O2 -pipe -g -feliminate-unused-debug-types  -fPIE   -o CMakeFiles/cmTC_a657f.dir/testCCompiler.c.o   -c /home/wildwindy/NFS/AWSSDK/sdkv2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp/testCCompiler.c

/opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -O2 -pipe -g -feliminate-unused-debug-types   -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -rdynamic CMakeFiles/cmTC_a657f.dir/testCCompiler.c.o  -o cmTC_a657f 
```

`testCCompiler.c` is very simple, something like:
https://github.com/Kitware/CMake/blob/master/Modules/CMakeTestCCompiler.cmake#L38

Did this work before the SDK included AWS-LC in its dependencies?

**Comment by torben-hansen** [comment] 2021-06-09 00:15
Adding to my previous comment. I do see that the first compiler check succeeded:
```
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
-- Check for working C compiler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -- works
```
Not sure how to explain that.

I assume you are using Poky and have build a cross-compilation environment. I'm not very familiar with Poky. Would you be able to share some information about how your build your cross-compilation environment? Without that I think it would be hard for me to produce it locally.

**Comment by torben-hansen** [comment] 2021-06-21 15:08
Hi, are you still experiencing the reported issue?

I would be happy to try and help resolve it.

**Comment by wildwindyevan** [comment] 2021-06-21 17:06
Sorry for my delay. I think  your first comment showed me  that  POKY can not build AWS-LC.
Farther more , In our  second comment  ，did you testing in crosscomplilation environment?
At last ,I uploaded my crosscomplilation environment  to  "https://thinkgrowledweb.s3.us-west-2.amazonaws.com/x86_64-pokysdk.tar.gz"
Hope it give you more information

**Comment by andrew-kaufman** [comment] 2021-07-01 22:03
Would you be able to provide more steps to reproduce this build issue using the cross-compilation environment that you provided?

**Comment by dkostic** [comment] 2021-07-28 15:02
Hi, just checking again if you'd be able to provide more steps to reproduce this build issue using the cross-compilation environment that you provided?

**Comment by andrew-kaufman** [comment] 2021-08-16 15:07
Since we have not received any other updates or information on this issue, we are going to close it for now as there is no further action for us to take. Please feel free to re-open this issue if you are able to provide us with any other information or updates.

**Closed by andrew-kaufman** 2021-08-16 15:07 UTC
