### ISSUE TITLE
Not able to crosscompile for armv7l

### ISSUE THREAD

**Issue by josecgon** [awslabs/aws-lc#186] opened 2021-07-02 07:11 UTC
### Problem:

Hello!

I'm trying to crosscompile the aws-iot-device-sdk-cpp-v2 code (main branch) for an armv7l

To start, I was following the instructions, and with the following script I compiled ir for x86_64 with no problems:

```
#!/bin/sh

WORKSPACE=/home/jose/repos/sdk-cpp-workspace
BUILD_TYPE="Debug"

cmake -DCMAKE_INSTALL_PREFIX=$WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_DEPS=ON ../aws-iot-device-sdk-cpp-v2
cmake --build . --target install --config $BUILD_TYPE
```

So then, I created a new script to crosscompile using a toolchain that I'm already using to crosscompile another projects:

```
#!/bin/sh

WORKSPACE=/home/jose/repos/sdk-cpp-workspace
BUILD_TYPE="Debug"

. /opt/poky/2.2.2/environment-setup-cortexa7hf-neon-vfpv4-poky-linux-gnueabi
cmake -DCMAKE_PREFIX_PATH=$WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_TOOLCHAIN_FILE=TRUE -DDISCARD_USER_INCLUDE=TRUE ../aws-iot-device-sdk-cpp-v2 
cmake --build . --target install
```

And doing it it seems that the aws-lc submodule is trying to compile an x86 assembly file.

Am I doing something wrong?

Thank you very much!

System information: for linux, below info can be collected by running `uname -srvmp`
 * CPU architecture: ARMv7  
 * CPU name: ARMv7 Processor rev 4
 * OS: Poky (Yocto Project Reference Distro) 2.2.2 (morty) - Linux 4.9.30

Build log: 

```
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
-- Check for working C compiler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++
-- Check for working CXX compiler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AWS CRT C++ v0.14.1
-- CMake 3.16.3
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_WINAPI_DESKTOP
-- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Success
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW - Failed
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Failed
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT - Failed
-- Performing Test HAS_64BIT_FILE_OFFSET_VIA_DEFINES
-- Performing Test HAS_64BIT_FILE_OFFSET_VIA_DEFINES - Success
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Looking for pthread_attr_setaffinity_np
-- Looking for pthread_attr_setaffinity_np - found
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- Checking for module 'libunwind-generic'
--   No package 'libunwind-generic' found
libunwind not found. Disabling unwind tests.
-- Go not found. Disabling some code generation and using pre-generated code in generated-src/
-- Perl not found. Disabling some code generation and using pre-generated code in generated-src/
-- Test stdalign_check.c passed, enabling AWS_LC_STDALIGN_AVAILABLE
-- Test builtin_swap_check.c passed, enabling AWS_LC_BUILTIN_SWAP_SUPPORTED
-- The ASM compiler identification is GNU
-- Found assembler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
Copying platform assembly files from /home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-lc/generated-src/linux-x86/crypto/ to /home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-cross-build/crt/aws-crt-cpp/crt/aws-lc/crypto
-- S2N found target: crypto
-- Using libcrypto from AWS-LC
-- Performing Test AWS_ARM32_CRC
-- Performing Test AWS_ARM32_CRC - Failed
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    DISCARD_USER_INCLUDE
    USE_TOOLCHAIN_FILE


-- Build files have been written to: /home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-cross-build
Scanning dependencies of target aws-c-common
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator.c.o
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator_sba.c.o
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/arch/arm/asm/cpuid.c.o
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/array_list.c.o
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/assert.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/byte_buf.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/cache.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/codegen.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/command_line_parser.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/common.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/condition_variable.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/date_time.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/device_random.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/encoding.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/error.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/fifo_cache.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/hash_table.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/lifo_cache.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/linked_hash_table.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/log_channel.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/log_formatter.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/log_writer.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/logging.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/lru_cache.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/math.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/memtrace.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/clock.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/condition_variable.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/device_random.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/environment.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/file.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/mutex.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/process.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/rw_lock.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/system_info.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/thread.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/time.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/priority_queue.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/process_common.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/promise.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/ref_count.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/resource_name.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/ring_buffer.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/statistics.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/string.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/task_scheduler.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/thread_scheduler.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/thread_shared.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/uuid.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/xml_parser.c.o
[  6%] Linking C static library libaws-c-common.a
[  6%] Built target aws-c-common
Scanning dependencies of target aws-c-compression
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/compression.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/huffman.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/huffman_testing.c.o
[  6%] Linking C static library libaws-c-compression.a
[  6%] Built target aws-c-compression
Scanning dependencies of target global_target
[  6%] Built target global_target
Scanning dependencies of target fipsmodule
[  6%] Building C object crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/bcm.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/fips_shared_support.c.o
[  6%] Building ASM object crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-x86.S.o
/home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-cross-build/crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/aesni-x86.S: Assembler messages:
/home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-cross-build/crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/aesni-x86.S:2513: Error: junk at end of line, first unrecognized character is `,'
make[2]: *** [crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/build.make:89: crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-x86.S.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1621: crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by andrew-kaufman** [comment] 2021-07-02 17:46
Would you be able to provide the toolchain file being used when attempting this cross-compile build? Also, how are you specifying this toolchain to the build? .

**Comment by josecgon** [comment] 2021-07-02 18:32
Sure.

I specify the toolchain with this line:  `. /opt/poky/2.2.2/environment-setup-cortexa7hf-neon-vfpv4-poky-linux-gnueabi` just before starting the cmake process (you can just execute the shell script I added on the question)

I'm not able to attach the toolchain because it is so heavy

Thank you very much for your help!

**Comment by torben-hansen** [comment] 2021-07-22 14:45
Can you upload the toolchain to e.g. an S3 bucket we can download?

It is difficult to reproduce this sort of issue without the toolchain.

Alternatively, specify how you generated the toolchain.

**Comment by torben-hansen** [comment] 2021-07-29 22:50
Hi,

Curious whether you have any updates on this?

Let us know. Happy to help.

**Comment by andrew-kaufman** [comment] 2021-08-16 15:06
Since we have not received any other updates or information on this issue, we are going to close it for now as there is no further action for us to take. Please feel free to re-open this issue if you are able to provide us with any other information or updates.

**Closed by andrew-kaufman** 2021-08-16 15:06 UTC
